services:
  workspace:
    build:
      context: ./dockerfiles/workspace
      dockerfile: Dockerfile
    volumes:
      - ./:/mnt
      - vscext:/home/developer/.vscode-server/extensions
    networks:
      - default

  rust-study:
    build:
      context: ./dockerfiles/rust_study
      dockerfile: Dockerfile
    volumes:
      - ./:/mnt
    networks:
      - default

volumes:
  vscext:
